### ISSUE TITLE
phrasing suggestion

### ISSUE THREAD

**Issue by BenTheElder** [dims/community-images#15]
I think the current phrasing is slightly misleading when it says "❌ are being pulled from Kubernetes community registries" and "✅ are good as they are NOT from Kubernetes community registries"

registry.k8s.io is to me a "kubernetes community registry" but shows up as green.

Maybe we can say something like: "Images in red ❌ are being pulled from **outdated** Kubernetes community registries. The Others marked in green ✅ are good as they do not use the outdated registries."

And consider adding gcr.io/google-containers to the list of outdated registries.

**Comment by dims** [comment]
@BenTheElder Done with both. thanks!

**Comment by BenTheElder** [comment]
Thanks dims! Cool project :-)
