### ISSUE TITLE
Surface more info - like namespaces where the problematic image is present

### ISSUE THREAD

**Issue by dims** [dims/community-images#7]
Optionally: list the namespaces where there is at least one problem Pod / pod template.

from @sftim https://kubernetes.slack.com/archives/CCK68P2Q2/p1677504435388339?thread_ts=1677416006.142059&cid=CCK68P2Q2

**Comment by yashodhanmohan** [comment]
Raised a PR for addressing this ^^

**Comment by dims** [comment]
Fixed in #26
